@startuml
state ShoppingCart {
    [*] --> Empty: ShoppingCartCreatedEvent
    Empty --> Collecting: ProductItemAddedEvent
    Collecting -left-> Empty: ProductItemRemovedEvent [items = 0]
    Collecting --> Collecting: ProductItemAddedEvent
    Collecting --> Collecting: ProductItemRemovedEvent [items > 0]
    Collecting --> Checkout
    Checkout --> [*]: ShoppingCartOrderedEvent
}

state OrderProcessing {
    ShoppingCart -> OrderProcessing: OrderPlacedEvent
    state startProcessing <<fork>>
    state creditReservation <<choice>>
    state endProcessing <<fork>>

    [*] --> creditReservation

    creditReservation --> [*]: OrderDeniedEvent [insufficient credits]
    creditReservation --> startProcessing: CreditReservedEvent

    startProcessing --> Invoice: InvoiceRequestedEvent
    Invoice --> Paid: InvoicePaidEvent
    Paid --> endProcessing

    startProcessing --> Shipped: ShipmentRequestedEvent
    Shipped --> Delivered: ShipmentDeliveredEvent
    Delivered --> endProcessing

    endProcessing --> [*]: OrderCompletedEvent
}
@enduml
